
# path
INCLUDEPATH += $$PWD/ccai\
               $$PWD/ccai/ccai_ollama\
               $$PWD/ccai/ccai_writer\
               $$PWD/ccai/ccai_writer/ccai_writer_chat\
               $$PWD/ccai/ccai_writer/ccai_writer_convert\
               $$PWD/ccai/ccai_writer/ccai_writer_display\
               $$PWD/ccai/ccai_writer/ccai_writer_generate\
               $$PWD/ccai/ccai_writer/ccai_writer_release\
               $$PWD/codeexample\
               $$PWD/codeexample/codeexample_export\
               $$PWD/codeexample/codeexample_import\
               $$PWD/codeexample/codeexample_view\
               $$PWD/collect\
               $$PWD/collect/collect_flush\
               $$PWD/communication\
               $$PWD/communication/com_network\
               $$PWD/communication/com_network/com_network_http\
               $$PWD/communication/com_network/com_network_tcpip\
               $$PWD/communication/com_network/com_network_tcpip/com_network_tcpip_server\
               $$PWD/communication/com_network/com_network_tcpip/com_network_tcpip_client\
               $$PWD/communication/com_serial\
               $$PWD/communication/com_serial/com_serial_port\
               $$PWD/components\
               $$PWD/components/buttonarray\
               $$PWD/draft\
               $$PWD/file\
               $$PWD/file/file_dir\
               $$PWD/file/file_md\
               $$PWD/file/file_pdf\
               $$PWD/file/file_pdf/file_pdf_pdfium\
               $$PWD/knowledge\
               $$PWD/moment\
               $$PWD/navigate\
               $$PWD/plan\
               $$PWD/plan/plandetail\
               $$PWD/plan/planstruct\
               $$PWD/project\
               $$PWD/project/codestruct\
               $$PWD/project/workstruct\
               $$PWD/projectcollect\
               $$PWD/script\
               $$PWD/script/script_bat\
               $$PWD/script/script_cmd\
               $$PWD/script/script_python\
               $$PWD/kernel\
               $$PWD/kernel/log\
               $$PWD/kernel/task\
               $$PWD/kernel/list\
               $$PWD/kernel/timer\
               $$PWD/kernel/mem\
               $$PWD/kernel/typeconvers\
               $$PWD/toolcollect\
               $$PWD/toolcollect/toolcollect_markmap\
               $$PWD/toolcollect/toolcollect_web\
               $$PWD/toolcollect/toolcollect_frp
