
# sources
SOURCES += \
    ccai/ccai.cpp \
    ccai/ccai_cfg.cpp \
    ccai/ccai_ollama/ccai_ollama.cpp \
    ccai/ccai_ollama/ccai_ollama_cfg.cpp \
    ccai/ccai_writer/ccai_writer.cpp \
    ccai/ccai_writer/ccai_writer_cfg.cpp \
    ccai/ccai_writer/ccai_writer_chat/ccai_writer_chat.cpp \
    ccai/ccai_writer/ccai_writer_chat/ccai_writer_chat_cfg.cpp \
    ccai/ccai_writer/ccai_writer_convert/ccai_writer_convert.cpp \
    ccai/ccai_writer/ccai_writer_convert/ccai_writer_convert_cfg.cpp \
    ccai/ccai_writer/ccai_writer_display/ccai_writer_display.cpp \
    ccai/ccai_writer/ccai_writer_display/ccai_writer_display_cfg.cpp \
    ccai/ccai_writer/ccai_writer_generate/ccai_writer_generate.cpp \
    ccai/ccai_writer/ccai_writer_generate/ccai_writer_generate_cfg.cpp \
    ccai/ccai_writer/ccai_writer_release/ccai_writer_release.cpp \
    ccai/ccai_writer/ccai_writer_release/ccai_writer_release_cfg.cpp \
    codeexample/codeexample.cpp \
    codeexample/codeexample_export/codeexample_export.cpp \
    codeexample/codeexample_export/codeexample_export_cfg.cpp \
    codeexample/codeexample_import/codeexample_import.cpp \
    codeexample/codeexample_import/codeexample_import_cfg.cpp \
    codeexample/codeexample_view/codeexample_view.cpp \
    codeexample/codeexample_view/codeexample_view_cfg.cpp \
    collect/collect.cpp \
    collect/collect_flush/collect_flush.cpp \
    collect/collect_flush/collect_flush_cfg.cpp \
    communication/com_network/com_network.cpp \
    communication/com_network/com_network_http/com_network_http.cpp \
    communication/com_network/com_network_http/com_network_http_cfg.cpp \
    communication/com_network/com_network_tcpip/com_network_tcpip.cpp \
    communication/com_network/com_network_tcpip/com_network_tcpip_cfg.cpp \
    communication/com_network/com_network_tcpip/com_network_tcpip_client/com_network_tcpip_client.cpp \
    communication/com_network/com_network_tcpip/com_network_tcpip_client/com_network_tcpip_client_cfg.cpp \
    communication/com_network/com_network_tcpip/com_network_tcpip_server/com_network_tcpip_server.cpp \
    communication/com_network/com_network_tcpip/com_network_tcpip_server/com_network_tcpip_server_cfg.cpp \
    communication/com_serial/com_serial.cpp \
    communication/com_serial/com_serial_port/com_serial_port.cpp \
    communication/com_serial/com_serial_port/com_serial_port_cfg.cpp \
    communication/communication.cpp \
    components/buttonarray/buttonarray.cpp \
    components/buttonarray/buttonarray_cfg.cpp \
    components/components.cpp \
    draft/draft.cpp \
    file/file.cpp \
    file/file_dir/file_dir.cpp \
    file/file_dir/file_dir_cfg.cpp \
    file/file_md/file_md.cpp \
    file/file_md/file_md_cfg.cpp \
    file/file_pdf/file_pdf.cpp \
    file/file_pdf/file_pdf_pdfium/file_pdf_pdfium.cpp \
    file/file_pdf/file_pdf_pdfium/file_pdf_pdfium_cfg.cpp \
    kernel/kernel.cpp \
    kernel/kernel_cfg.cpp \
    kernel/list/list.cpp \
    kernel/list/list_cfg.cpp \
    kernel/log/log.cpp \
    kernel/log/log_cfg.cpp \
    kernel/mem/mem.cpp \
    kernel/mem/mem_cfg.cpp \
    kernel/task/task.cpp \
    kernel/task/task_cfg.cpp \
    kernel/timer/timer.cpp \
    kernel/timer/timer_cfg.cpp \
    kernel/typeconvers/typeconvers.cpp \
    kernel/typeconvers/typeconvers_cfg.cpp \
    knowledge/knowledge.cpp \
    main.cpp \
    mainwindow.cpp \
    moment/moment.cpp \
    navigate/navigate.cpp \
    plan/plan.cpp \
    plan/plandetail/plandetail.cpp \
    plan/plandetail/plandetail_cfg.cpp \
    plan/planstruct/planstruct.cpp \
    plan/planstruct/planstruct_cfg.cpp \
    project/codestruct/project_codestruct.cpp \
    project/codestruct/project_codestruct_cfg.cpp \
    project/project.cpp \
    project/workstruct/project_workstruct.cpp \
    project/workstruct/project_workstruct_cfg.cpp \
    projectcollect/projectcollect.cpp \
    script/script.cpp \
    script/script_bat/script_bat.cpp \
    script/script_bat/script_bat_cfg.cpp \
    script/script_cmd/script_cmd.cpp \
    script/script_cmd/script_cmd_cfg.cpp \
    script/script_python/script_python.cpp \
    script/script_python/script_python_cfg.cpp \
    script/script_website/script_website.cpp \
    script/script_website/script_website_cfg.cpp \
    toolcollect/toolcollect.cpp \
    toolcollect/toolcollect_frp/toolcollect_frp.cpp \
    toolcollect/toolcollect_frp/toolcollect_frp_cfg.cpp \
    toolcollect/toolcollect_markmap/toolcollect_markmap.cpp \
    toolcollect/toolcollect_markmap/toolcollect_markmap_cfg.cpp \
    toolcollect/toolcollect_web/toolcollect_web.c \
    toolcollect/toolcollect_web/toolcollect_web_cfg.c

# headers
HEADERS += \
    cc_type.h \
    ccai/ccai.h \
    ccai/ccai_cfg.h \
    ccai/ccai_ollama/ccai_ollama.h \
    ccai/ccai_ollama/ccai_ollama_cfg.h \
    ccai/ccai_writer/ccai_writer.h \
    ccai/ccai_writer/ccai_writer_cfg.h \
    ccai/ccai_writer/ccai_writer_chat/ccai_writer_chat.h \
    ccai/ccai_writer/ccai_writer_chat/ccai_writer_chat_cfg.h \
    ccai/ccai_writer/ccai_writer_convert/ccai_writer_convert.h \
    ccai/ccai_writer/ccai_writer_convert/ccai_writer_convert_cfg.h \
    ccai/ccai_writer/ccai_writer_display/ccai_writer_display.h \
    ccai/ccai_writer/ccai_writer_display/ccai_writer_display_cfg.h \
    ccai/ccai_writer/ccai_writer_generate/ccai_writer_generate.h \
    ccai/ccai_writer/ccai_writer_generate/ccai_writer_generate_cfg.h \
    ccai/ccai_writer/ccai_writer_release/ccai_writer_release.h \
    ccai/ccai_writer/ccai_writer_release/ccai_writer_release_cfg.h \
    cctools_cfg.h \
    codeexample/codeexample.h \
    codeexample/codeexample_export/codeexample_export.h \
    codeexample/codeexample_export/codeexample_export_cfg.h \
    codeexample/codeexample_import/codeexample_import.h \
    codeexample/codeexample_import/codeexample_import_cfg.h \
    codeexample/codeexample_view/codeexample_view.h \
    codeexample/codeexample_view/codeexample_view_cfg.h \
    collect/collect.h \
    collect/collect_flush/collect_flush.h \
    collect/collect_flush/collect_flush_cfg.h \
    communication/com_network/com_network.h \
    communication/com_network/com_network_http/com_network_http.h \
    communication/com_network/com_network_http/com_network_http_cfg.h \
    communication/com_network/com_network_tcpip/com_network_tcpip.h \
    communication/com_network/com_network_tcpip/com_network_tcpip_cfg.h \
    communication/com_network/com_network_tcpip/com_network_tcpip_client/com_network_tcpip_client.h \
    communication/com_network/com_network_tcpip/com_network_tcpip_client/com_network_tcpip_client_cfg.h \
    communication/com_network/com_network_tcpip/com_network_tcpip_server/com_network_tcpip_server.h \
    communication/com_network/com_network_tcpip/com_network_tcpip_server/com_network_tcpip_server_cfg.h \
    communication/com_network/com_network_tcpip/com_network_tcpip_type.h \
    communication/com_serial/com_serial.h \
    communication/com_serial/com_serial_port/com_serial_port.h \
    communication/com_serial/com_serial_port/com_serial_port_cfg.h \
    communication/communication.h \
    components/buttonarray/buttonarray.h \
    components/buttonarray/buttonarray_cfg.h \
    components/components.h \
    draft/draft.h \
    file/file.h \
    file/file_dir/file_dir.h \
    file/file_dir/file_dir_cfg.h \
    file/file_md/file_md.h \
    file/file_md/file_md_cfg.h \
    file/file_pdf/file_pdf.h \
    file/file_pdf/file_pdf_pdfium/file_pdf_pdfium.h \
    file/file_pdf/file_pdf_pdfium/file_pdf_pdfium_cfg.h \
    kernel/kernel.h \
    kernel/kernel_cfg.h \
    kernel/list/list.h \
    kernel/list/list_cfg.h \
    kernel/log/log.h \
    kernel/log/log_cfg.h \
    kernel/mem/mem.h \
    kernel/mem/mem_cfg.h \
    kernel/task/task.h \
    kernel/task/task_cfg.h \
    kernel/timer/timer.h \
    kernel/timer/timer_cfg.h \
    kernel/typeconvers/typeconvers.h \
    kernel/typeconvers/typeconvers_cfg.h \
    knowledge/knowledge.h \
    mainwindow.h \
    moment/moment.h \
    navigate/navigate.h \
    plan/plan.h \
    plan/plandetail/plandetail.h \
    plan/plandetail/plandetail_cfg.h \
    plan/planstruct/planstruct.h \
    plan/planstruct/planstruct_cfg.h \
    project/codestruct/project_codestruct.h \
    project/codestruct/project_codestruct_cfg.h \
    project/project.h \
    project/workstruct/project_workstruct.h \
    project/workstruct/project_workstruct_cfg.h \
    projectcollect/projectcollect.h \
    script/script.h \
    script/script_bat/script_bat.h \
    script/script_bat/script_bat_cfg.h \
    script/script_cmd/script_cmd.h \
    script/script_cmd/script_cmd_cfg.h \
    script/script_python/script_python.h \
    script/script_python/script_python_cfg.h \
    script/script_website/script_website.h \
    script/script_website/script_website_cfg.h \
    toolcollect/toolcollect.h \
    toolcollect/toolcollect_frp/toolcollect_frp.h \
    toolcollect/toolcollect_frp/toolcollect_frp_cfg.h \
    toolcollect/toolcollect_markmap/toolcollect_markmap.h \
    toolcollect/toolcollect_markmap/toolcollect_markmap_cfg.h \
    toolcollect/toolcollect_web/toolcollect_web.h \
    toolcollect/toolcollect_web/toolcollect_web_cfg.h

# ui
FORMS += \
    ccai/ccai.ui \
    ccai/ccai_writer/ccai_writer.ui \
    codeexample/codeexample.ui \
    collect/collect.ui \
    communication/com_network/com_network.ui \
    communication/com_serial/com_serial.ui \
    communication/communication.ui \
    components/components.ui \
    draft/draft.ui \
    file/file.ui \
    file/file_pdf/file_pdf.ui \
    knowledge/knowledge.ui \
    mainwindow.ui \
    moment/moment.ui \
    navigate/navigate.ui \
    plan/plan.ui \
    project/project.ui \
    projectcollect/projectcollect.ui \
    script/script.ui \
    toolcollect/toolcollect.ui
